name: mobile_app_flutter
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Logo.png
    - assets/images/BottomRight.png
    - assets/images/BottomLeft.png
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/pizza.jpg
    - assets/images/burger.jpg
    - assets/images/sandwich.jpg
    - assets/images/resturent1.jpg
    - assets/images/resturent2.jpg
