apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: foodapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: rashad123123/order-service:v2
          ports:
            - containerPort: 5003
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/order-service-db
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: foodapp
spec:
  selector:
    app: order-service
  ports:
    - port: 5003
      targetPort: 5003
  type: NodePort
