apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: foodapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: rashad123123/auth-service:v6
          ports:
            - containerPort: 5001
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/auth-service-db
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: foodapp
spec:
  selector:
    app: auth-service
  ports:
    - port: 5001
      targetPort: 5001
  type: NodePort
